insert into Stato ( Stato ) values ( "Da leggere" ) ;
insert into Stato ( Stato ) values ( "Parzialmente letto" ) ;
insert into Stato ( Stato ) values ( "Letto" ) ;
insert into Stato ( Stato ) values ( "Di forte interesse" ) ;
insert into Stato ( Stato ) values ( "Di medio interesse" ) ;
insert into Stato ( Stato ) values ( "Di scarso interesse" ) ;

insert into Valutazioni ( Valutazione ) values ( 1 ) ;
insert into Valutazioni ( Valutazione ) values ( 2 ) ;
insert into Valutazioni ( Valutazione ) values ( 3 ) ;
insert into Valutazioni ( Valutazione ) values ( 4 ) ;
insert into Valutazioni ( Valutazione ) values ( 5 ) ;

insert into Categorie ( Categoria ) values ( "neuroscienze" ) ;
insert into Categorie ( Categoria ) values ( "robotica e intelligenza artificiale" ) ;
insert into Categorie ( Categoria ) values ( "biologia" ) ;
insert into Categorie ( Categoria ) values ( "scienze naturali" ) ;
insert into Categorie ( Categoria ) values ( "zoologia" ) ;
insert into Categorie ( Categoria ) values ( "paleontologia" ) ;
insert into Categorie ( Categoria ) values ( "astronomia, astrofisica e cosmologia" ) ;
insert into Categorie ( Categoria ) values ( "fisiologia" ) ;
insert into Categorie ( Categoria ) values ( "medicina, patologia e chirurgia" ) ;
insert into Categorie ( Categoria ) values ( "fisica" ) ;
insert into Categorie ( Categoria ) values ( "trasporti" ) ;
insert into Categorie ( Categoria ) values ( "energia e politiche energetiche" ) ;
insert into Categorie ( Categoria ) values ( "scienze della terra e dell'atmosfera" ) ;
insert into Categorie ( Categoria ) values ( "climatologia e meteorologia" ) ;
insert into Categorie ( Categoria ) values ( "informatica, elettronica, telecomunicazioni" ) ;
insert into Categorie ( Categoria ) values ( "archeologia e civilta' antiche" ) ;
insert into Categorie ( Categoria ) values ( "biotecnologie" ) ;
insert into Categorie ( Categoria ) values ( "genetica" ) ;
insert into Categorie ( Categoria ) values ( "farmacologia, tossicologia e strumenti diagnostici" ) ;
insert into Categorie ( Categoria ) values ( "nanotecnologie" ) ;
insert into Categorie ( Categoria ) values ( "antropologia, paletnologia e paleoantropologia" ) ;
insert into Categorie ( Categoria ) values ( "evoluzione" ) ;
insert into Categorie ( Categoria ) values ( "alimentazione e nutrizione" ) ;
insert into Categorie ( Categoria ) values ( "spazio, astronautica e aeronautica" ) ;
insert into Categorie ( Categoria ) values ( "arte, letteratura e musica" ) ;
insert into Categorie ( Categoria ) values ( "matematica e logica matematica" ) ;
insert into Categorie ( Categoria ) values ( "armi e politica degli armamenti" ) ;
insert into Categorie ( Categoria ) values ( "ingegneria, tecnologia, industria" ) ;
insert into Categorie ( Categoria ) values ( "storia della scienza e della tecnica" ) ;
insert into Categorie ( Categoria ) values ( "ecologia e ambiente" ) ;
insert into Categorie ( Categoria ) values ( "linguaggio, scrittura e comunicazione" ) ;
insert into Categorie ( Categoria ) values ( "chimica" ) ;
insert into Categorie ( Categoria ) values ( "politiche sanitarie" ) ;
insert into Categorie ( Categoria ) values ( "psicologia, psichiatria e scienze cognitive" ) ;
insert into Categorie ( Categoria ) values ( "scienze sociali e demografia" ) ;
insert into Categorie ( Categoria ) values ( "storia" ) ;
insert into Categorie ( Categoria ) values ( "botanica" ) ;
insert into Categorie ( Categoria ) values ( "politiche della scienza" ) ;
insert into Categorie ( Categoria ) values ( "scienza dei materiali" ) ;
insert into Categorie ( Categoria ) values ( "agricoltura e zootecnia" ) ;
insert into Categorie ( Categoria ) values ( "economia" ) ;
insert into Categorie ( Categoria ) values ( "sport" ) ;
insert into Categorie ( Categoria ) values ( "comportamento animale" ) ;
insert into Categorie ( Categoria ) values ( "bioetica" ) ;
insert into Categorie ( Categoria ) values ( "politiche internazionali" ) ;
insert into Categorie ( Categoria ) values ( "statistica" ) ;
insert into Categorie ( Categoria ) values ( "politica e sistemi elettorali" ) ;
insert into Categorie ( Categoria ) values ( "scienze forensi" ) ;
insert into Categorie ( Categoria ) values ( "architettura e urbanistica" ) ;
insert into Categorie ( Categoria ) values ( "filosofia della scienza" ) ;
insert into Categorie ( Categoria ) values ( "quaderni di matematica" ) ;

